### ISSUE TITLE
CursorError on certain combination of IEs

### ISSUE THREAD

**Issue by sten69** [britram/libfc#10]
Put these into a message:

  interfaceName 'eth'
  ingressInterface 0x12345678
  octetDeltaCount 0x1020304050607080

and libfc will die:

[tik40x:build]$ LD_LIBRARY_PATH=~/lib:~/lib64 ./fctest --run_test=Messages/Regressions
Running 1 test case...
unknown location(0): fatal error in "Message265": std::exception: CursorError: end of buffer caching offsets: input data not IPFIX?
/home/neuhaust/libfc/test/TestMessages.cpp(8708): last checkpoint

**\* 1 failure detected in test suite "FC Test"

This test is run as part of the Messages/Regressions test suite.

**Comment by britram** [comment]
fixed. post-varlen iteration only worked if _all_ IEs after the first varlen IE were varlen -- which is good practice. but not what the protocol specifies. :)
