### ISSUE TITLE
fcold::SwitchImp (i.e., libfc::PlacementCollector) needs start and end message events

### ISSUE THREAD

**Issue by britram** [britram/libfc#11]
Placement collectors should provide their inheritors with start and end message events. This is probably doable by merging PlacementContentHandler with PlacementCollector.

**Comment by sten69** [comment]
Done. Note that fcold doesn't compile due to changes not by me.

**Comment by sten69** [comment]
To use the new feature, derive from PlacementCollector and implement start_message().
