### ISSUE TITLE
libfc::PlacementExporter should allow changing of observation domain

### ISSUE THREAD

**Issue by britram** [britram/libfc#12]
Since fcold::SwitchImp will carry forward some information from the V9 observation domain analogue, we'll need a call in PlacementExporter that ensures a particular observation domain (and if the present message is not empty and the observation domain is different, flushes the present message to create a new one with the new observation domain)

**Comment by sten69** [comment]
Done. Note that fcold branch doesn't compile, but not because of anything that I've done.
